name: Deploy to ESP32

on:
  push:
    branches:
      - main

jobs:
  deploy-esp32:
    runs-on: [self-hosted, prod]
    environment: Prod
    name: Deploy to ESP32 Devices

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate config.hpp
        run: |
          echo $CONF_FILE | base64 -d > src/config.hpp
          echo "Generated src/config.hpp with CONF_FILE content."
          cat src/config.hpp

      - name: Build project
        run: |
          ${{ secrets.PIO }} run -e esp32OTA
          ls
          cd .pio
          ls
          cd build
          ls
          cd esp32OTA
          ls

      - name: Request IPs from API
        id: get_ips
        run: |
          response=$(curl -s "${{ secrets.API_URL }}/api/workflow/getIps")
          echo "IPs=$response" >> $GITHUB_ENV

      - name: Process IP list
        id: process_ips
        run: |
          ips=${{ env.IPs }}
          echo "Received IPs: $ips"

          IFS=',' read -r -a ip_array <<< "${ips//[\[\]\"\ ]/}"

          for ip in "${ip_array[@]}"; do
            echo "Pinging IP: $ip"
            if ping -c 1 $ip &> /dev/null; then
              echo "IP $ip is reachable. Uploading..."
              python3 /home/phsapp/.platformio/packages/framework-arduinoespressif32/tools/espota.py \
                --ip $ip \
                --port 8081 \
                --host_ip 0.0.0.0 \
                --debug --progress
            else
              echo "IP $ip is not reachable. Skipping."
            fi
          done

    env:
      CONF_FILE: ${{ secrets.CONF_FILE }}
      API_URL: ${{ secrets.API_URL }}
