name: Deploy to ESP32

on:
  push:
    branches:
      - main

jobs:
  deploy-esp32:
    runs-on: self-hosted
    environment: Develop
    name: Deploy to ESP32 Devices

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Python3
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip

      - name: Install PlatformIO
        run: |
          curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
          python3 get-platformio.py

      - name: Request IPs from API
        id: get_ips
        run: |
          response=$(curl -s "${{ secrets.API_URL }}/api/workflow/getIps")
          echo "IPs=$response" >> $GITHUB_ENV

      - name: Process IP list
        id: process_ips
        run: |
          ips=${{ env.IPs }}
          echo "Received IPs: $ips"

          IFS=',' read -r -a ip_array <<< "${ips//[\[\]\"\ ]/}"

          for ip in "${ip_array[@]}"; do
            echo "Pinging IP: $ip"
            if ping -c 1 $ip &> /dev/null; then
              echo "IP $ip is reachable. Uploading..."
              pio upload -e esp32OTA --upload-port $ip || echo "Upload to $ip failed."
            else
              echo "IP $ip is not reachable. Skipping."
            fi
          done

    env:
      API_URL: ${{ secrets.API_URL }}
